import { OSCard } from "./OSCard";
import { StatusCard } from "./StatusCard";
import { DesktopCard } from "./DesktopCard";
import { PackagesCard } from "./PackagesCard";
import { NetworkCard } from "./NetworkCard";
import { DiskCard } from "./DiskCard";
import { HardwareCard } from "./HardwareCard";

export default function View() {
  return (
    <div className="flex flex-col gap-6 p-6">
      <header>
        <h1 className="text-3xl lg:text-4xl font-bold">System Information</h1>
      </header>
      <main className="grid grid-cols-[repeat(auto-fit,minmax(375px,max-content))] gap-6 max-w-full">
        <div className="flex flex-col gap-6">
          <OSCard />
          <StatusCard />
          <DesktopCard />
          <PackagesCard />
        </div>
        <div className="flex flex-col gap-6">
          <NetworkCard />
          <DiskCard />
        </div>
        <div>
          <HardwareCard />
        </div>
      </main>
      <footer>
        <p className="text-muted-foreground">🄯 Fyra Labs, generated by Boba</p>
      </footer>
    </div>
  );
}
