"use client";

import { OSCard } from "./OSCard";
import { StatusCard } from "./StatusCard";
import { DesktopCard } from "./DesktopCard";
import { PackagesCard } from "./PackagesCard";
import { NetworkCard } from "./NetworkCard";
import { DiskCard } from "./DiskCard";
import { HardwareCard } from "./HardwareCard";
import { infoSchema } from "./schema";
import { use } from "react";

const hexToArrayBuffer = (hex: string) => {
  const arr = hex.match(/.{1,2}/g)!.map((byte) => parseInt(byte, 16));
  return new Uint8Array(arr).buffer;
};

const decryptSystemInfo = async (
  data: ArrayBuffer,
  decryptionPayload: string,
) => {
  const decryptonPayloadData = hexToArrayBuffer(decryptionPayload);
  // 32 bytes for key, 12 bytes for nonce
  if (decryptonPayloadData.byteLength != 44) {
    throw new Error(
      "The decryption payload provided is invalid, must be 44 bytes",
    );
  }

  const keyData = decryptonPayloadData.slice(0, 32);
  const nonceData = decryptonPayloadData.slice(32);

  const key = await crypto.subtle.importKey(
    "raw",
    keyData,
    { name: "AES-GCM" },
    false,
    ["decrypt"],
  );
  const plaintext = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: nonceData },
    key,
    data,
  );

  const infoObject = JSON.parse(new TextDecoder().decode(plaintext));

  return infoSchema.parse(infoObject);
};

export default function View({ data }: { data: ArrayBuffer }) {
  const info = use(decryptSystemInfo(data, window.location.hash.slice(1)));
  console.log(info);

  return (
    <div className="flex flex-col gap-6 p-6">
      <header>
        <h1 className="text-3xl lg:text-4xl font-bold">System Information</h1>
      </header>
      <main className="grid grid-cols-[repeat(auto-fit,minmax(375px,max-content))] gap-6 max-w-full">
        <div className="flex flex-col gap-6">
          <OSCard {...info.os} />
          <StatusCard {...info.status} />
          <DesktopCard {...info.desktop} />
          <PackagesCard {...info.packages} />
        </div>
        <div className="flex flex-col gap-6">
          <NetworkCard {...info.network_devices} />
          <DiskCard {...info.disks} />
        </div>
        <div>
          <HardwareCard {...info.hardware} />
        </div>
      </main>
      <footer>
        <p className="text-muted-foreground">🄯 Fyra Labs, generated by Boba</p>
      </footer>
    </div>
  );
}
